config/routes.rb
Rails.application.routes.draw do

  get 'bookings/create'
  get 'users/dashboard'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get '/dashboard', to: 'users#dashboard'
  resources :users, only: [:show]
  resources :cycles, only: [:index, :show, :new, :create, :destroy] do
    resource :bookings, only: [:create]
  end
  get 'test', to: 'pages#test'
  get 'bookings/:id/confirmation', to: 'bookings#confirmation', as: :confirmation

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :cycle
  belongs_to :user
end

app/models/cycle.rb
class Cycle < ApplicationRecord

  include PgSearch::Model
  pg_search_scope :search_by_fields,
    against: [ :brand, :color, :category, :town],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  has_many :bookings
  belongs_to :user


  validates :brand, presence: true
  validates :color, presence: true
  validates :category, presence: true
  validates :price, presence: true
  validates :location, presence: true
  validates :town, presence: true

  BRAND = Cycle.select(:brand).map(&:brand).uniq.reject(&:blank?)
  COLOR = Cycle.select(:color).map(&:color).uniq.reject(&:blank?)
  CATEGORY = Cycle.select(:category).map(&:category).uniq.reject(&:blank?)
  TOWN = Cycle.select(:town).map(&:town).uniq.reject(&:blank?)

end

app/models/user.rb
class User < ApplicationRecord

  has_many :cycles
  has_many :bookings_as_owner, through: :cycles, source: :bookings
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :description])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:email])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @cycle = Cycle.find(params[:cycle_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.cycle = @cycle
    if @booking.save
      redirect_to dashboard_path
    else
      render 'cycles/show'
    end
  end

  def confirmation



  end

  private
  def booking_params
    params.require(:booking).permit(:pick_up_date, :Description, :user_id)
  end



end

app/controllers/cycles_controller.rb
class CyclesController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:search].present?
      @brand = params[:search][:brand]
      @color = params[:search][:color]
      @category = params[:search][:category]
      @town = params[:search][:town]
      if [@brand, @color, @category, @town].join.empty?
        @cycles = Cycle.all
      else
      params_for_search = [@brand, @color, @category, @town].join(' ')
      @cycles = Cycle.search_by_fields(params_for_search)
      end
    elsif params[:query].present?
      @cycles = Cycle.search_by_fields(params[:query])
    else
      @cycles = Cycle.all
    end
  end


  def show
    @cycle = Cycle.find(params[:id])
    @booking = Booking.new
    @cycles = Cycle.geocoded
    @markers = [
      {
        lat: @cycle.latitude,
        lng: @cycle.longitude
      }
    ]
  end


  def create
    @cycle = Cycle.new(cycle_params)
    @cycle.user = current_user

    if @cycle.save
      redirect_to dashboard_path
    else
      render 'new'
    end
  end

  def new
    @cycle = Cycle.new
  end

  def destroy
    @cycle = Cycle.find(params[:id])
    @cycle.destroy
    redirect_to '/cycles/new', :notice => "Your cycle has been deleted"
  end

  private
  def cycle_params
    params.require(:cycle).permit(:brand, :color, :category, :price, :description, :location, :photo)
  end

end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @cycles = Cycle.all
  end

  def test
    render 'layouts/test'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!

  def dashboard
    @cycles = current_user.bookings.map { |booking| booking.cycle }
    @bookings = current_user.bookings
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/cycles_helper.rb
module CyclesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/confirmation.html.erb
<div class="d-flex justify-content-center" >
<h1>Thank you for booking this cycle.</h1>

</div>

app/views/cycles/index.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">


<div class="container p-2">
<%= simple_form_for :search, url: cycles_path, method:'GET', html: {class: 'form-inline'} do |f| %>
    <div class="form-group mb-2 mx-2">
          <%= f.input :brand, collection: Cycle::BRAND, class: 'form-control', required: false, selected: @brand, include_blank: 'All' %>
    </div>
    <div class="form-group mx-2 mb-2">
          <%= f.input :color, collection: Cycle::COLOR, class: 'form-control mr-2', required: false, selected: @color, include_blank: 'All' %>
    </div>
    <div class="form-group mx-2 mb-2">
          <%= f.input :category, collection: Cycle::CATEGORY, class: 'form-control mr-2', required: false, selected: @category, include_blank: 'All' %>
    </div>
    <div class="form-group mx-2 mb-2">
          <%= f.input :town, collection: Cycle::TOWN, class: 'form-control mr-2', required: false, selected: @town, include_blank: 'All' %>
    </div>
    <div class="form-group">
          <%= f.submit "Search", class: "btn-yellow" %>
    </div>
      <% end %>
<br>

<% if @cycles.empty? %>
<h1>No cycles meet your criteria</h1>
<h2>Please try another search:</h2>
<% else  %>


<div class="container mt-2 mb-3">
  <h1>Cycles available near you</h1>

  <div class="row">
    <% @cycles.each do |cycle| %>
      <div class="col-md-4 mb-5">
        <div class="small-card">
          <%= link_to cycle_path(cycle), id:"cyclephoto" do %>
          <%= image_tag cycle.photo %>

          <div class="d-flex justify-content-front ml-3 mt-3 ">
            <h3><%= cycle.brand %></h3>
            <!-- <h2>Product title!</h2> -->
          </div>
          <div class="small-card-infos d-flex justify-content-between text-center" style="font-size: 18px; font-weight: bolder;">
            <h5 class="card-text"><%= cycle.category.capitalize %></h5>
            <p class="card-price">¥<%= cycle.price %></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  </div>
  <% end  %>
</div>

app/views/cycles/new.html.erb
<h1>New</h1>

<div class="container">
  <%= simple_form_for(@cycle) do |f| %>
  <%= f.error_notification %>

  <%= f.input :brand, label: "Brand" %>
  <%= f.input :color, label: "Color" %>
  <%= f.input :category, label: "Category" %>
  <%= f.input :price, label: "Price" %>
  <%= f.input :description, label: "Description" %>
  <%= f.input :location, label: "Location" %>
  <%= f.input :photo, label: "just put in string for now I'll use cloudinary on this - NS" %>

  <%= f.button :submit, class: "btn-primary" %>
  <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
<% end %>
</div>


<%= link_to 'go home', root_path %>

app/views/cycles/show.html.erb
<div class="container mt-3">

<div class="container justify-content-around mt-5">



  <div class="big-card">
    <h2><%= @cycle.brand.capitalize%></h2>
      <br>
      <br>
      <div class="info-list">
      <div style="list-style-type: none; display: inline-block;">
        <li><strong>Category </strong></li>
        <li><strong>Color </strong></li>
        <li><strong>Location </strong></li>
        <li><strong>Price </strong></li>
        <li><strong>Contact name </strong></li>
        <li><strong>Note </strong></li>
      </div>


      <div style="list-style-type: none; display: inline-block; margin-left: 1em;">
        <li><%= @cycle.category.capitalize %></li>
        <li><%= @cycle.color.capitalize %></li>
        <li><%= @cycle.town.capitalize %></li>
        <li>¥<%= @cycle.price %></li>
        <li><%= @cycle.user.first_name.capitalize %></li>
        <li><%= @cycle.description.capitalize %></li>
      </div>
    </div>
    <%= image_tag @cycle.photo, alt: "current cycle" %>
  </div>

  <br><br>


  <div
  id="map"

  style="width: 90%;
  height: 300px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="pk.eyJ1IjoibmFvdG9zdXp1a2kxMSIsImEiOiJjazI1Z3hrd2IwNGF0M3BvZzJ2d2tsdTF4In0.MrCZy7dD9c-SBp5N2FVTNA"
></div>

  <br><br>

  <%= simple_form_for([@cycle, @booking]) do |f| %>
  <%= f.error_notification %>
    <%=f.input :Description, label: "Contact the seller to purchase." %>
    <%= f.button :submit, 'Request to purchase', class: "btn-yellow" %>
    <%= link_to root_path do %>
      <%= f.button :button, "Cancel", type: "reset", class: "btn-blk" %>
    <% end %>
  <% end %>
  <br>
  <br>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Japancycle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>

  <body>
    <div class="content">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>

    </div>
    <div class="footer-adjust">
      <%= render "shared/footer" %>
    </div>
    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="banner-container">
  <div class="stacked-container">
    <div class="text-container">
      <h1 id="tagline">Shop for your next cycle with ease </h1>
      <div class="overlay">
        <div class="search-content">
          <p>Search cycles</p>
          <%= simple_form_for :search, url: cycles_path, method: :get do |f| %>
          <div class="search-form-control form-group">
            <input id= "yellow-form" class="form-control string required" type="text" name="query" id="banner-typed-text" />
            <button name="button" type="submit" class="btn btn-flat">
              <i class="fas fa-search"></i> Search
            </button>

            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= video_tag("bike.mp4", autoplay: "", loop: "", muted: "", class: "video-container") %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer" style="text-align: center;">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-japancycle">
  <div class="logo" style="align-items: center">
    <i class="fas fa-biking"></i>
    <%= link_to 'JapanCycle', root_path, id: "logo-font"%>
  </div>


  <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span>
  </button> <%#= link_to "#", class: "navbar-brand" do %> <%#= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %> <#% end %> <%#= link_to "#", class: "navbar-brand" do %> <#%= image_tag
  "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %> <#% end %> -->

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav justify-content-right">

      <% if user_signed_in? %>
        <li id="fa-bell" class="nav-item dropdown">

          <div data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
            <i class="fas fa-bell fa-lg"></i></div>
            <div id="notification-text" class="dropdown-menu">
              <%= link_to dashboard_path do %>
                <div class="dropdown-item text-dark w-100 h-100">Notifications</div>
              <% end %>

            </div>
        </li>
        <li class="nav-item">
          <%= link_to "List a Cycle", new_cycle_path , class: "nav-link" %>
        <li class="nav-item">
          <%= link_to "Explore", cycles_path, class: "nav-link" %>
        </li>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Explore", cycles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/dashboard.html.erb
<div class="container m-5 mx-auto">
  <div class="row">
    <div class="col-12 align-items-center">
       <h1 style="font-family: Muli; font-size: 24px;"><i class="fas fa-address-book" style="font-size: 20px;"></i> My Account</h1>
        <h1 style="font-family: Muli; font-size: 40px;">Request Status</h1>
        <div class="yellow-border-x" style="width: 500px;"></div>
    </div>
    <div class="col-12 mt-5 mb-3">
      <%@cycles.each do |cycle|%>
      <div class="mb-3">
      <div class="big-card small">
        <div class="info-list-dashboard">
          <div style="list-style-type: none; display: inline-block;">
            <li><strong>Brand </strong></li>
            <li><strong>Location </strong></li>
            <li><strong>Price </strong></li>
            <li><strong>Seller </strong></li>
            <li><strong>Contact </strong></li>
            <li><strong>Status </strong></li>
         </div>

          <div style="list-style-type: none; display: inline-block; margin-left: 1em;">
            <li><%= cycle.brand %></li>
            <li><%= cycle.town.capitalize %></li>
            <li>¥<%= cycle.price %></li>
            <li><%= cycle.user.first_name.capitalize %></li>
            <li><%= cycle.user.email %></li>
            <li>Pending approval</li>
          </div>
        </div>
        <%= image_tag cycle.photo, alt: "current cycle" %>
      </div>
      </div>
      <% end %>
    </div>

  </div>
</div>